<template><div><h1 id="crypto" tabindex="-1"><a class="header-anchor" href="#crypto" aria-hidden="true">#</a> Crypto</h1>
<h1 id="核心类" tabindex="-1"><a class="header-anchor" href="#核心类" aria-hidden="true">#</a> 核心类</h1>
<div class="custom-container tip"><p class="custom-container-title">数据加密、支持常用的加密方式和不常用的加密</p>
</div>
<h3 id="encrypt" tabindex="-1"><a class="header-anchor" href="#encrypt" aria-hidden="true">#</a> <code v-pre>encrypt</code></h3>
<ul>
<li>加密方法</li>
<li><code v-pre>参数 (data, crypto, params) =&gt; string</code>
<ul>
<li>data <code v-pre>加密数据</code></li>
<li>crypto <code v-pre>加密密策略(见下方配置表）</code></li>
<li>params <code v-pre>加密参数(见下方配置表）</code></li>
</ul>
</li>
</ul>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> data <span class="token operator">=</span> <span class="token string">'gf-ui-core'</span>
<span class="token keyword">const</span> key <span class="token operator">=</span> <span class="token string">'gf-key'</span>
<span class="token keyword">const</span> iv <span class="token operator">=</span> <span class="token string">'gf-iv'</span>

<span class="token comment">// 非对称加密算法</span>
Crypto<span class="token punctuation">.</span><span class="token function">encrypt</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'MD5'</span> <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token comment">// 9e8322b3ba7c75f882682fb06a5798d5</span>
Crypto<span class="token punctuation">.</span><span class="token function">encrypt</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'SHA1'</span> <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token comment">// 4664894d711bc939a4088f80b79e9532c10a4852</span>
Crypto<span class="token punctuation">.</span><span class="token function">encrypt</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'SHA3'</span> <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token comment">// 338b59adc01a5e46a63ea10f9afbc722b5f7db3742d407ce8fac78ebe4d3faf97a7707917468f3abc0639fa8d8462a5210304d8a23d477716baa19bfb3e37487</span>
Crypto<span class="token punctuation">.</span><span class="token function">encrypt</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'SHA224'</span> <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token comment">// a3b60616940d27032f8a82f2b546e8bc9786946525649ee1ee1cf55e</span>
Crypto<span class="token punctuation">.</span><span class="token function">encrypt</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'SHA256'</span> <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token comment">// aaf10bba46001e1e2e589e004078a0bbdd65753da9afbfcd5c855f6df79ac46d</span>
Crypto<span class="token punctuation">.</span><span class="token function">encrypt</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'SHA384'</span> <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token comment">// a25b86b5248fbfd084cf75d23240e971a00c42b586be8a91b337c9485ac81580bb18a74640b6a499d65baf15d1c242cd</span>
Crypto<span class="token punctuation">.</span><span class="token function">encrypt</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'SHA512'</span> <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token comment">// c3ba425db972ecde5f57594c02041c6e7b0619e62276488a2eeaf7f522b71da8749e6dc4308adb9362cea455d649fd7885f535dddab17d580b22ebdc6ee906cc</span>
Crypto<span class="token punctuation">.</span><span class="token function">encrypt</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'HmacMD5'</span><span class="token punctuation">,</span> <span class="token literal-property property">hmac</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token comment">// ebb76581e49a0107bbf18e1665304f72</span>
Crypto<span class="token punctuation">.</span><span class="token function">encrypt</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'HmacSHA1'</span><span class="token punctuation">,</span> <span class="token literal-property property">hmac</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token comment">// d21bc5810d0a7a274289bc9319236bfa9a07d97b</span>
Crypto<span class="token punctuation">.</span><span class="token function">encrypt</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'HmacSHA3'</span><span class="token punctuation">,</span> <span class="token literal-property property">hmac</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token comment">// 0ac39cb2c6a170fa3cf89cd1ca0b9f9a5a53e8ff46cae395d23a4f7b22db7d78757a8af891254506132e69c4355210a05f1f8943681d6501d0255c78de9b1ea4</span>

<span class="token comment">// 对称加密算法</span>
Crypto<span class="token punctuation">.</span><span class="token function">encrypt</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'Base64'</span><span class="token punctuation">,</span> <span class="token literal-property property">encoding</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> key<span class="token punctuation">,</span> iv <span class="token punctuation">}</span><span class="token punctuation">)</span>  <span class="token comment">// ...</span>
Crypto<span class="token punctuation">.</span><span class="token function">encrypt</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'DES'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> key<span class="token punctuation">,</span> iv <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token comment">// 4ba7d000435c6b61db49777f9e530701</span>
<span class="token operator">...</span><span class="token punctuation">.</span>等
</code></pre></div><h3 id="decrypt" tabindex="-1"><a class="header-anchor" href="#decrypt" aria-hidden="true">#</a> <code v-pre>decrypt</code></h3>
<ul>
<li>
<p>解密方法<span class="colorff0066 font-bold"> <strong>【只针对对称加密算法】</strong></span></p>
</li>
<li>
<p><code v-pre>参数 (data, crypto, params) =&gt; string</code></p>
<ul>
<li>data <code v-pre>加密数据</code></li>
<li>crypto <code v-pre>加密密策略(见下方配置表）</code></li>
<li>params <code v-pre>加密参数(见下方配置表）</code></li>
</ul>
</li>
</ul>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> data <span class="token operator">=</span> <span class="token string">'gf-ui-core'</span>
<span class="token keyword">const</span> key <span class="token operator">=</span> <span class="token string">'gf-key'</span>
<span class="token keyword">const</span> iv <span class="token operator">=</span> <span class="token string">'gf-iv'</span>
Crypto<span class="token punctuation">.</span><span class="token function">decrypt</span><span class="token punctuation">(</span><span class="token string">'4ba7d000435c6b61db49777f9e530701'</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'DES'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> key<span class="token punctuation">,</span> iv <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token operator">===</span> data <span class="token comment">// true</span>
</code></pre></div><div class="custom-container tip"><p class="custom-container-title">非对称加密算法类型</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token literal-property property">md5</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'MD5'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">sha1</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'SHA1'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">sha3</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'SHA3'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">sha224</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'SHA224'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">sha256</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'SHA256'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">sha384</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'SHA384'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">sha512</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'SHA512'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">hmacmd5</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'HmacMD5'</span><span class="token punctuation">,</span> <span class="token literal-property property">hmac</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">hmacsha1</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'HmacSHA1'</span><span class="token punctuation">,</span> <span class="token literal-property property">hmac</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">hmacsha3</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'HmacSHA3'</span><span class="token punctuation">,</span> <span class="token literal-property property">hmac</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">hmacsha224</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'HmacSHA224'</span><span class="token punctuation">,</span> <span class="token literal-property property">hmac</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">hmacsha256</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'HmacSHA256'</span><span class="token punctuation">,</span> <span class="token literal-property property">hmac</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">hmacsha384</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'HmacSHA384'</span><span class="token punctuation">,</span> <span class="token literal-property property">hmac</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">hmacsha512</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'HmacSHA512'</span><span class="token punctuation">,</span> <span class="token literal-property property">hmac</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">pbkdf2</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'PBKDF2'</span><span class="token punctuation">,</span> <span class="token literal-property property">params</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">keySize</span><span class="token operator">:</span> <span class="token number">128</span> <span class="token operator">/</span> <span class="token number">32</span><span class="token punctuation">,</span> <span class="token literal-property property">iterations</span><span class="token operator">:</span> <span class="token number">10</span> <span class="token punctuation">}</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">evpkdf</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'EvpKDF'</span><span class="token punctuation">,</span> <span class="token literal-property property">params</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">keySize</span><span class="token operator">:</span> <span class="token number">128</span> <span class="token operator">/</span> <span class="token number">32</span><span class="token punctuation">,</span> <span class="token literal-property property">iterations</span><span class="token operator">:</span> <span class="token number">10</span> <span class="token punctuation">}</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">ripemd160</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'RIPEMD160'</span><span class="token punctuation">,</span> <span class="token literal-property property">params</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">keySize</span><span class="token operator">:</span> <span class="token number">128</span> <span class="token operator">/</span> <span class="token number">32</span><span class="token punctuation">,</span> <span class="token literal-property property">iterations</span><span class="token operator">:</span> <span class="token number">10</span> <span class="token punctuation">}</span> <span class="token punctuation">}</span>
</code></pre></div></div>
<div class="custom-container tip"><p class="custom-container-title">对称加密算法类型</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token literal-property property">base64</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'Base64'</span><span class="token punctuation">,</span> <span class="token literal-property property">encoding</span><span class="token operator">:</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">aes</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'AES'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">des</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'DES'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">rc4</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'RC4'</span><span class="token punctuation">,</span> <span class="token literal-property property">iv</span><span class="token operator">:</span> <span class="token boolean">false</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">rabbit</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'Rabbit'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">rabbitlegacy</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">'RabbitLegacy'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token literal-property property">none</span><span class="token operator">:</span> <span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">''</span> <span class="token punctuation">}</span>
</code></pre></div></div>
</div></template>
